/*
 * CriteriaParserEnvironment.java
 *
 * Created on November 5, 2004, 3:27 PM
 */

package un.asytax.taxation;

import un.asygate.taxation.TaxationParserEnvironment;
import un.kernel.util.AbstractParserEnvironment;
import un.kernel.util.RuleSyntaxTokens;


/**
 * 
 * @author u_site TaxationParserEnvironment
 */
//public class ImpValNoteParserEnvironment extends AbstractParserEnvironment implements RuleSyntaxTokens {
public class ImpValNoteParserEnvironment extends TaxationParserEnvironment implements RuleSyntaxTokens {
/*
	public String[][] getVariables() {
		String[][] variables = { { "%", "0", "001", 
			lng("Inv"), 
			lng("Invoice amount in foreign currency") },
				{ "$", "0", "002", 
			lng("InvCur"), 
			lng("Invoice currency code") },
				{ "%", "0", "003", 
			lng("InvCurRat"), 
			lng("Invoice currency exchange rate") },
				{ "%", "1", "004", 
			lng("InvNcy"), 
			lng("Invoice amount in national currency") },
				{ "%", "0", "005", 
			lng("Efr"), 
			lng("External freight amount in foreign currency") },
				{ "$", "0", "006", 
			lng("EfrCur"), 
			lng("External freight currency code") },
				{ "%", "0", "007", 
			lng("EfrCurRat"), 
			lng("External freight currency exchange rate") },
				{ "%", "1", "008", 
			lng("EfrNcy"), 
			lng("External freight amount in national currency") },
				{ "%", "0", "009", 
			lng("Ins"), 
			lng("Insurance amount in foreign currency") },
				{ "$", "0", "010", 
			lng("InsCur"), 
			lng("Insurance currency code") },
				{ "%", "0", "011", 
			lng("InsCurRat"), 
			lng("Insurance currency exchange rate") },
				{ "%", "1", "012", 
			lng("InsNcy"), 
			lng("Insurance amount in national currency") },
				{ "%", "0", "013", 
			lng("Otc"), 
			lng("Other cost amount in foreign currency") },
				{ "$", "0", "014", 
			lng("OtcCur"), 
			lng("Other cost currency code") },
				{ "%", "0", "015", 
			lng("OtcCurRat"), 
			lng("Other cost currency exchange rate") },
				{ "%", "1", "016", 
			lng("OtcNcy"), 
			lng("Other cost amount in national currency") },
				{ "%", "0", "017", 
			lng("Ifr"), 
			lng("Internal freight amount in foreign currency") },
				{ "$", "0", "018", 
			lng("IfrCur"), 
			lng("Internal freight currency code") },
				{ "%", "0", "019", 
			lng("IfrCurRat"), 
			lng("Internal freight currency exchange rate") },
				{ "%", "1", "020", 
			lng("IfrNcy"), 
			lng("Internal freight amount in national currency") },
				{ "%", "0", "021", 
			lng("Ded"), 
			lng("Deductions amount in foreign currency") },
				{ "$", "0", "022", 
			lng("DedCur"), 
			lng("Deductions currency code") },
				{ "%", "0", "023", 
			lng("DedCurRat"), 
			lng("Deductions currency exchange rate") },
				{ "%", "1", "024", 
			lng("DedNcy"), 
			lng("Deductions amount in national currency") },
				{ "%", "1", "025", 
			lng("TotalMass"), 
			lng("Total gross mass") }, { "%", "1", "026", 
			lng("TotalCost"), 
			lng("Total costs") },
				{ "%", "1", "027", 
			lng("CIFNcy"), 
			lng("CIF value in national currency") },
				{ "%", "0", "030", 
			lng("ItmInv"), 
			lng("Item invoice amount in foreign currency") },
				{ "$", "0", "031", 
			lng("ItmInvCur"), 
			lng("Item invoice currency code") },
				{ "%", "0", "032", 
			lng("ItmInvCurRat"), 
			lng("Item invoice currency exchange rate") },
				{ "%", "1", "033", 
			lng("ItmInvNcy"), 
			lng("Item invoice amount in national currency") },
				{ "%", "1", "034", 
			lng("ItmEfr"), 
			lng("Item external freight amount in foreign currency") },
				{ "$", "0", "035", 
			lng("ItmEfrCur"), 
			lng("Item external freight currency code") },
				{ "%", "0", "036", 
			lng("ItmEfrCurRat"), 
			lng("Item external freight currency exchange rate") },
				{ "%", "1", "037", 
			lng("ItmEfrNcy"), 
			lng("Item external freight amount in national currency") },
				{ "%", "1", "038", 
			lng("ItmIns"), 
			lng("Item insurance amount in foreign currency") },
				{ "$", "0", "039", 
			lng("ItmInsCur"), 
			lng("Item insurance currency code") },
				{ "%", "0", "040", 
			lng("ItmInsCurRat"), 
			lng("Item insurance currency exchange rate") },
				{ "%", "1", "041", 
			lng("ItmInsNcy"), 
			lng("Item insurance amount in national currency") },
				{ "%", "1", "042", 
			lng("ItmOtc"), 
			lng("Item other cost amount in foreign currency") },
				{ "$", "0", "043", 
			lng("ItmOtcCur"), 
			lng("Item other cost currency code") },
				{ "%", "0", "044", 
			lng("ItmOtcCurRat"), 
			lng("Item other cost currency exchange rate") },
				{ "%", "1", "045", 
			lng("ItmOtcNcy"), 
			lng("Item other cost amount in national currency") },
				{ "%", "1", "046", 
			lng("ItmIfr"), 
			lng("Item internal freight amount in foreign currency") },
				{ "$", "0", "047", 
			lng("ItmIfrCur"), 
			lng("Item internal freight currency code") },
				{ "%", "0", "048", 
			lng("ItmIfrCurRat"), 
			lng("Item internal freight currency exchange rate") },
				{ "%", "1", "049", 
			lng("ItmIfrNcy"), 
			lng("Item internal freight amount in national currency") },
				{ "%", "1", "050", 
			lng("ItmDed"), 
			lng("Item deductions amount in foreign currency") },
				{ "$", "0", "051", 
			lng("ItmDedCur"), 
			lng("Item deductions currency code") },
				{ "%", "0", "052", 
			lng("ItmDedCurRat"), 
			lng("Item deductions currency exchange rate") },
				{ "%", "1", "053", 
			lng("ItmDedNcy"), 
			lng("Item deductions amount in national currency") },
				{ "%", "1", "054", 
			lng("ItmTotalCost"), 
			lng("Item total costs") },
				{ "%", "0", "055", 
			lng("ItmADJRATE"), 
			lng("Item adjustment rate") },
				{ "%", "1", "056", 
			lng("ItmCIFNcy"), 
			lng("Item CIF value in national currency") },
				{ "%", "1", "057", 
			lng("ItmStatVal"), 
			lng("Item statistical value") },
				{ "$", "0", "080", 
			lng("CuoCod"), 
			lng("Customs office code") },
				{ "$", "0", "081", 
			lng("MOTBorder"), 
			lng("Mode of transportation at the border") },
				{ "$", "0", "082", 
			lng("MOTInLand"), 
			lng("Mode of transportation inland") },
				{ "%", "0", "083", 
			lng("GrossMass"), 
			lng("Gross mass for the item") },
				{ "$", "0", "085", 
			lng("CtyOrigCod"), 
			lng("Country of origin code") },
				{ "$", "0", "086", 
			lng("ValMethod"), 
			lng("Itm: Valuation method") },
				{ "$", "0", "106", 
			lng("Manifest REf"), 
			lng("G.S.: Manifest reference number") }, };
		return variables;
	}
*/
	public String[][] getFunctions() {
		String[][] functions = { { "01", 
			lng("RoundInf(x)"), 
			lng("if N <= x < N + 1 then N") },
				{ "02", 
			lng("RoundSup(x)"), 
			lng("if N < x <= N + 1 then N + 1") },
				{ "03", 
			lng("Round(x)"), 
			lng("if N <= x < N + 0.5 then N else N + 1") }, { "04", 
			lng("Min(x, y)"), 
			lng("if x < y then x else y") },
				{ "05", 
			lng("Max(x, y)"), 
			lng("if x > y then x else y") }, { "06", 
			lng("Sqr(x)"), 
			lng("Square x * x") },
				{ "07", 
			lng("Abs(x)"), 
			lng("Absolute value of x") }, { "08", 
			lng("JulianDate(s)"), 
			lng("Convert date to julian number") }, };
		return functions;
	}
/*
	public String[][] getKeywords() {
		String[][] keywords = { { "R", 
			lng("Rule"), 
			lng("Criteria \"criteria name\" ;") },
				{ "I", 
			lng("If"), 
			lng("If condition Then statements [Else statements] Endif") },
				{ "T", 
			lng("Then"), 
			lng("If condition Then statements [Else statements] Endif") },
				{ "E", 
			lng("Else"), 
			lng("If condition Then statements [Else statements] Endif") },
				{ "N", 
			lng("Endif"), 
			lng("If condition Then statements [Else statements] Endif") },
				{ "&", 
			lng("and"), 
			lng("condition 1 and condition 2") }, { "|", 
			lng("or"), 
			lng("condition 1 or condition 2") },
				{ "!", 
			lng("not"), 
			lng("not (condition 1)") }, { "(", "(", 
			lng("open parenthesis") },
				{ ")", 
			lng(")"), 
			lng("close parenthesis") }, { "=", 
			lng("IS"), 
			lng("data element IS expression; (assignment statement)") },
				{ "=", 
			lng(":="), 
			lng("data element := expression; (assignment statement)") },
				{ "==", 
			lng("="), 
			lng("expression 1 = expression 2") }, { "==", 
			lng("EQ"), 
			lng("expression 1 EQ expression 2") },
				{ "<", 
			lng("<"), 
			lng("expression 1 < expression 2") }, { "<", 
			lng("LT"), 
			lng("expression 1 LT expression 2") },
				{ "<=", 
			lng("<="), 
			lng("expression 1 <= expression 2") }, { "<=", 
			lng("LE"), 
			lng("expression 1 LE expression 2") },
				{ ">", 
			lng(">"), 
			lng("expression 1 > expression 2") }, { ">", 
			lng("GT"), 
			lng("expression 1 GT expression 2") },
				{ ">=", 
			lng(">="), 
			lng("expression 1 >= expression 2") }, { ">=", 
			lng("GE"), 
			lng("expression 1 GE expression 2") },
				{ "!=", 
			lng("<>"), 
			lng("expression 1 <> expression 2") }, { "!=", 
			lng("NE"), 
			lng("expression 1 NE expression 2") },
				{ ":", 
			lng(";"), 
			lng("end of statement") }, { "+", "+", 
			lng("expression 1 + expression 2") },
				{ "+", 
			lng("Plus"), 
			lng("expression 1 Plus expression 2") }, { "-", "-", 
			lng("expression 1 - expression 2") },
				{ "-", 
			lng("Minus"), 
			lng("expression 1 Minus expression 2") }, { "*", "*", 
			lng("expression 1 * expression 2") },
				{ "*", 
			lng("Mul"), 
			lng("expression 1 Mul expression 2") }, { "/", "/", 
			lng("expression 1 / expression 2") },
				{ "/", 
			lng("Div"), 
			lng("expression 1 Div expression 2") }, { ",", 
			lng(","), 
			lng("function( expression 1, expression2, ...)") }, };
		return keywords;
	}
*/
	/** Creates a new instance of CriteriaParserEnvironment */
	public ImpValNoteParserEnvironment() {
		super();
	}
/*
	private static String lng(String property) {
		return so.i18n.IntlObj.createMessage("un.asytax", property);
	}
*/
}
